name: AutoForge CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest

      - name: Add repo to PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Debug import path
        run: |
          python -c "import os,sys; print('WS:', os.environ.get('GITHUB_WORKSPACE')); print('PYTHONPATH:', os.environ.get('PYTHONPATH')); print('sys.path[0:3]:', sys.path[:3])"
          python -c "import app; print('Imported app OK')"

      - name: Run tests
        run: pytest -q

  docker_build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t autoforge-ai .
