name: Deploy AutoForge API (SP)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create deployment zip
        run: |
          zip -r release.zip . \
            -x ".git/*" ".github/*" "__pycache__/*" "*.pyc" ".venv/*" "tests/*"

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy via CLI (Zip Deploy)
        run: |
          az webapp deploy \
            --resource-group autoforge-project \
            --name AutoForge-api \
            --type zip \
            --src-path release.zip
