name: Deploy to Azure Web App (F1 Code)

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          # must match your Web App name exactly
          app-name: AutoForge-api
          # paste the entire XML of the publish profile into this secret
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          # zip & push the repo (Oryx will build from requirements.txt)
          package: .
